# Generated by Django 4.1.11 on 2023-10-03 16:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('userId', models.UUIDField(default=uuid.UUID('ba84d922-d40c-451e-bd41-6a41144fd2c0'), unique=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 3, 57, 573855))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 3, 57, 574864))),
                ('status', models.TextField(default='offline', max_length=100)),
                ('profileUrl', models.CharField(max_length=50)),
                ('profileImage', models.CharField(max_length=50)),
                ('isBanned', models.BooleanField(default=False)),
            ],
        ),
    ]
