# Generated by Django 4.1.4 on 2023-01-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='RegisterUsers',
        ),
    ]
