# Generated by Django 5.2.4 on 2025-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstName',
            field=models.CharField(blank=True, default='UnKnown', max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
