# Generated by Django 4.1.11 on 2023-10-03 16:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusers',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 4, 8, 98805)),
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 4, 8, 98805)),
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('5775014a-3165-4d7a-9bd4-a65950078a58'), unique=True),
        ),
    ]
