# Generated by Django 4.1.11 on 2023-10-03 16:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_registerusers_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusers',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 4, 18, 965995)),
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 4, 18, 965995)),
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='userId',
            field=models.UUIDField(default=uuid.UUID('609c7fee-358c-4b60-bc38-8297671284e1'), unique=True),
        ),
    ]
