# Generated by Django 5.2.4 on 2025-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_verified_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='locationName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
